OPENAI_API_KEY = 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
SERPAPI_API_KEY = d34b420bc8603ac534de3c155c264cbbee96bc041b332207bc857587d887e2f9
HUGGINGFACEHUB_API_KEY = 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

PINECONE_API_KEY = 914a0f4d-fe87-46d5-8ee8-abaddf1155da
PINECONE_ENV = gcp-starter